language: node_js

cache:
  directories:
    - ~/.npm
    
node_js:
  - '8'
  - '10'
  - '12'
  
services:
  - mongodb

git:
  depth: 3

branches:
  only:
    - master

env:
  global:
    - NODE_ENV=test
    - PORT=3000
    - JWT_SECRET=justanothersecret
    - JWT_EXPIRATION_MINUTES=15
    - MONGO_URI=mongodb://localhost:27017/
    - MONGO_URI_TESTS=mongodb://localhost:27017/test
    - EMAIL_PORT=587
    - EMAIL_HOST=smtp-relay.sendinblue.com
    - EMAIL_USERNAME=smtp-username
    - EMAIL_PASSWORD=smtp-password

script: yarn validate
after_success: yarn coverage
